#!/usr/bin/env node
// `npm run build:shim` (cloudflare.md §G): validate + minify-check the guest
// shim modules (`src/engines/guest-shim.js` and `guest-globals.js`) with
// esbuild and emit them as string constants (`src/engines/guest-shim.bundled.ts`)
// so the Worker can hand them to the Dynamic Worker loader as
// `modules["shim.js"]` / `modules["globals.js"]`. The output is checked in;
// re-run after any shim edit (`test/engines.test.ts` fails if it is stale).

import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dir = resolve(here, "..", "src", "engines");
const out = resolve(dir, "guest-shim.bundled.ts");

// Line endings are normalized to LF: a Windows checkout (core.autocrlf)
// hands this script CRLF, and without normalizing, the generated module —
// and its source hashes — would differ from the Linux build CI diffs
// against (`git diff --exit-code` in .github/workflows/ci.yml).
const lf = (s) => s.replace(/\r\n/g, "\n");
const sources = {
  shim: lf(readFileSync(resolve(dir, "guest-shim.js"), "utf8")),
  globals: lf(readFileSync(resolve(dir, "guest-globals.js"), "utf8")),
};

// esbuild parse check (syntax errors fail the build); the shim ships
// unminified so guest stack traces stay readable. esbuild resolves from
// wrangler's dependency tree; absent, the parse check is skipped (the
// engines unit tests still catch a broken shim).
try {
  const { transformSync } = await import("esbuild");
  for (const source of Object.values(sources)) transformSync(source, { loader: "js", format: "esm" });
} catch (e) {
  if (e && e.code === "ERR_MODULE_NOT_FOUND") {
    console.warn("[build:shim] esbuild not resolvable — skipping the parse check");
  } else {
    throw e;
  }
}

const hashOf = (s) => createHash("sha256").update(s).digest("hex").slice(0, 16);
const shimHash = hashOf(sources.shim);
const globalsHash = hashOf(sources.globals);
const banner = `// GENERATED by scripts/build-shim.mjs from guest-shim.js + guest-globals.js — do not edit.
// Source hashes: shim ${shimHash}, globals ${globalsHash}

/// The guest shim as text, handed to the Dynamic Worker loader as
/// \`modules["shim.js"]\` (cloudflare.md §E.2).
export const GUEST_SHIM: string = ${JSON.stringify(sources.shim)};

/// The shim's globals module (\`modules["globals.js"]\`), evaluated before
/// the deployed bundle.
export const GUEST_GLOBALS: string = ${JSON.stringify(sources.globals)};

/// sha256(guest-shim.js)[0..16] / sha256(guest-globals.js)[0..16] —
/// staleness checks for the generated module.
export const GUEST_SHIM_SOURCE_HASH = ${JSON.stringify(shimHash)};
export const GUEST_GLOBALS_SOURCE_HASH = ${JSON.stringify(globalsHash)};
`;
writeFileSync(out, banner);
console.log(
  `[build:shim] ${out} (shim ${sources.shim.length} bytes ${shimHash}, globals ${sources.globals.length} bytes ${globalsHash})`,
);
