#!/usr/bin/env node
// `npm run build:shim` (cloudflare.md §G): validate + minify-check
// `src/engines/guest-shim.js` with esbuild and emit it as a string module
// (`src/engines/guest-shim.bundled.ts`) so the Worker can hand it to the
// Dynamic Worker loader as `modules["shim.js"]`. The output is checked in;
// re-run after any shim edit (`test/engines.test.ts` fails if it is stale).

import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "..", "src", "engines", "guest-shim.js");
const out = resolve(here, "..", "src", "engines", "guest-shim.bundled.ts");

const source = readFileSync(src, "utf8");

// esbuild parse check (syntax errors fail the build); the shim ships
// unminified so guest stack traces stay readable. esbuild resolves from
// wrangler's dependency tree; absent, the parse check is skipped (the
// engines unit tests still catch a broken shim).
try {
  const { transformSync } = await import("esbuild");
  transformSync(source, { loader: "js", format: "esm" });
} catch (e) {
  if (e && e.code === "ERR_MODULE_NOT_FOUND") {
    console.warn("[build:shim] esbuild not resolvable — skipping the parse check");
  } else {
    throw e;
  }
}

const hash = createHash("sha256").update(source).digest("hex").slice(0, 16);
const banner = `// GENERATED by scripts/build-shim.mjs from guest-shim.js — do not edit.
// Source hash: ${hash}

/// The guest shim as text, handed to the Dynamic Worker loader as
/// \`modules["shim.js"]\` (cloudflare.md §E.2).
export const GUEST_SHIM: string = ${JSON.stringify(source)};

/// sha256(guest-shim.js)[0..16] — staleness check for the generated module.
export const GUEST_SHIM_SOURCE_HASH = ${JSON.stringify(hash)};
`;
writeFileSync(out, banner);
console.log(`[build:shim] ${out} (${source.length} bytes, hash ${hash})`);
