// Port of the `#[cfg(test)]` module in `rs2-core/src/message/media_type.rs`:
// the extension map is a cross-host contract, so both hosts must name the same
// media type for the same file and probe the same extension-less candidates.
// Both tables are generated by `scripts/gen-media-types.mjs` from one source —
// these tests are what says the generated data is usable, not just present.
import { describe, expect, it } from "vitest";
import { MediaType } from "../src/runtime/media-type";
import { CANONICAL_EXTENSIONS, EXTENSION_TABLE, NEGOTIABLE_EXTENSIONS } from "../src/runtime/media-type-table";

describe("extension map", () => {
  it("maps media, font and long-tail extensions", () => {
    const cases: Array<[string, string]> = [
      ["clips/intro.mp4", "video/mp4"],
      ["clips/intro.webm", "video/webm"],
      ["clips/intro.MOV", "video/quicktime"],
      ["audio/theme.mp3", "audio/mpeg"],
      ["audio/theme.ogg", "audio/ogg"],
      ["fonts/inter.woff2", "font/woff2"],
      ["favicon.ico", "image/vnd.microsoft.icon"],
      ["docs/report.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
      ["book.epub", "application/epub+zip"],
      ["captions.vtt", "text/vtt"],
      ["stream.m3u8", "application/vnd.apple.mpegurl"],
      ["archive.tar.gz", "application/gzip"],
      ["photo.heic", "image/heic"],
    ];
    for (const [path, essence] of cases) {
      expect(MediaType.forPath(path).essence(), path).toBe(essence);
    }
  });

  // A `.ts` in a tenant's files is TypeScript source, not the MPEG transport
  // stream nginx (and so mime-db) calls it.
  it("applies RS2's pins over the aggregate", () => {
    expect(MediaType.forPath("src/app.ts").essence()).toBe("application/typescript");
    expect(MediaType.forPath("src/app.tsx").essence()).toBe("application/typescript");
    expect(MediaType.forPath("feed.xml").essence()).toBe("application/xml");
    expect(MediaType.forPath("app.js").essence()).toBe("text/javascript");
  });

  it("never sniffs an unknown path", () => {
    expect(MediaType.forPath("a/b/mystery").essence()).toBe("application/octet-stream");
    expect(MediaType.forPath("a/b/c.not-an-extension").essence()).toBe("application/octet-stream");
  });

  // Bulk media maps by name but must not join the extension-less probe list —
  // each candidate there costs a store probe on a miss.
  it("keeps bulk media out of negotiation", () => {
    const negotiable = MediaType.knownExtensions().map(([ext]) => ext);
    expect(negotiable[0]).toBe("html");
    expect(negotiable).toContain("png");
    expect(negotiable.length).toBe(NEGOTIABLE_EXTENSIONS.length);
    for (const ext of ["mp4", "webm", "mp3", "woff2", "ico", "docx"]) {
      expect(negotiable, ext).not.toContain(ext);
      expect(MediaType.fromExtension(ext), ext).toBeDefined();
    }
    for (const [ext, mt] of MediaType.knownExtensions()) {
      expect(mt.essence(), `negotiable .${ext} has no media type`).not.toBe("application/octet-stream");
    }
  });

  // The reverse map names a server-named file (keyless POST). Every entry must
  // map back to its own essence, or the file would be served as something
  // other than what was posted.
  it("round-trips every canonical extension", () => {
    for (const [essence, ext] of CANONICAL_EXTENSIONS) {
      expect(MediaType.fromExtension(ext)?.essence(), `${essence} -> .${ext}`).toBe(essence);
    }
    const posted: Array<[string, string]> = [
      ["video/mp4", "mp4"],
      ["audio/mpeg", "mp3"],
      ["image/jpeg", "jpg"],
      ["text/javascript", "js"],
      ["application/pdf", "pdf"],
    ];
    for (const [essence, ext] of posted) {
      expect(new MediaType(essence).canonicalExtension(), essence).toBe(ext);
    }
    expect(new MediaType("application/x-not-a-real-type").canonicalExtension()).toBeUndefined();
  });

  // The tables are binary-searched, so a sort slip would silently lose rows.
  it("keeps the generated tables sorted and whole", () => {
    expect(EXTENSION_TABLE.length).toBeGreaterThan(1000);
    for (let i = 1; i < EXTENSION_TABLE.length; i++) {
      expect(EXTENSION_TABLE[i - 1]![0] < EXTENSION_TABLE[i]![0], `EXTENSION_TABLE at ${i}`).toBe(true);
    }
    for (let i = 1; i < CANONICAL_EXTENSIONS.length; i++) {
      expect(CANONICAL_EXTENSIONS[i - 1]![0] < CANONICAL_EXTENSIONS[i]![0], `CANONICAL_EXTENSIONS at ${i}`).toBe(true);
    }
  });

  // Both hosts read tables generated from one source; a lookup that disagreed
  // would be a divergence in what a client is served.
  it("finds every row it stores", () => {
    for (const [ext, essence] of EXTENSION_TABLE) {
      expect(MediaType.fromExtension(ext)?.essence(), ext).toBe(essence);
    }
  });
});
