// Typed tenant/mount configuration. The catalogue document is JSON Schema
// draft-07 derived from the Rust types; this host ships the same JSON as a
// checked-in fixture generated by the Rust side (cloudflare.md §I.19) so
// `GET /services/catalogue` is byte-identical on both hosts. Regenerate
// `src/fixtures/catalogue.json` whenever `rs2-core/src/config_schema.rs`
// changes (see the fixture's provenance note in the package README).

import catalogueFixture from "../fixtures/catalogue.json";
import { RsError } from "./error";
import type { Json, JsonObject } from "./error";
import { retryFromConfig } from "./retry";
import type { RetryPolicy } from "./retry";

export function catalogue(): JsonObject {
  return catalogueFixture as unknown as JsonObject;
}

/// One mount of a tenant config (`MountSpec`, strict: unknown keys are a 400).
export interface MountSpec {
  path: string;
  service: string;
  config: JsonObject;
}

export interface CatalogueRef {
  name: string;
  url: string;
}

/// Successor to Restspace's `services.json` (`TenantConfig`).
export interface TenantConfig {
  mounts: MountSpec[];
  operatorRoles: string | undefined;
  retry: RetryPolicy | undefined;
  auth: Json | undefined;
  cors: Json | undefined;
  catalogues: CatalogueRef[];
  secrets: Json | undefined;
  /// Worker-only tenant-level knob (cloudflare.md §C.3): `{"sink": "none"}`.
  logging: Json | undefined;
}

function invalid(detail: string): RsError {
  return RsError.badRequest(`invalid tenant config: ${detail}`);
}

/// Parse a raw config document the way serde deserializes `TenantConfig`:
/// `mounts` required; every mount `{path, service, config?}` with no other
/// keys; typed optional top-level fields.
export function parseTenantConfig(value: Json): TenantConfig {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw invalid("expected an object");
  const mountsRaw = value.mounts;
  if (mountsRaw === undefined) throw invalid("missing field `mounts`");
  if (!Array.isArray(mountsRaw)) throw invalid("invalid type: `mounts` must be an array");
  const mounts: MountSpec[] = mountsRaw.map((m, i) => {
    if (!m || typeof m !== "object" || Array.isArray(m)) throw invalid(`mounts[${i}]: expected an object`);
    for (const k of Object.keys(m)) {
      if (k !== "path" && k !== "service" && k !== "config") {
        throw invalid(`unknown field \`${k}\`, expected one of \`path\`, \`service\`, \`config\``);
      }
    }
    if (typeof m.path !== "string") throw invalid("missing field `path`");
    if (typeof m.service !== "string") throw invalid("missing field `service`");
    const config = m.config;
    let cfg: JsonObject;
    if (config === undefined || config === null) cfg = {};
    else if (typeof config === "object" && !Array.isArray(config)) cfg = config;
    else throw invalid("invalid type: `config` must be an object");
    return { path: m.path, service: m.service, config: cfg };
  });
  const operatorRoles = value.operatorRoles;
  if (operatorRoles !== undefined && operatorRoles !== null && typeof operatorRoles !== "string") {
    throw invalid("invalid type: `operatorRoles` must be a string");
  }
  let retry: RetryPolicy | undefined;
  if (value.retry !== undefined && value.retry !== null) {
    retry = retryFromConfig(value.retry);
    if (!retry) throw invalid("invalid `retry` policy");
  }
  const cats: CatalogueRef[] = [];
  if (value.catalogues !== undefined && value.catalogues !== null) {
    if (!Array.isArray(value.catalogues)) throw invalid("invalid type: `catalogues` must be an array");
    for (const c of value.catalogues) {
      if (!c || typeof c !== "object" || Array.isArray(c) || typeof c.name !== "string" || typeof c.url !== "string") {
        throw invalid("catalogues entries need `name` and `url`");
      }
      cats.push({ name: c.name, url: c.url });
    }
  }
  return {
    mounts,
    operatorRoles: typeof operatorRoles === "string" ? operatorRoles : undefined,
    retry,
    auth: value.auth ?? undefined,
    cors: value.cors ?? undefined,
    catalogues: cats,
    secrets: value.secrets ?? undefined,
    logging: value.logging ?? undefined,
  };
}
